services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: newme:local
    network_mode: host
    environment:
      NEWME_DATA_PATH: /data
      SECRET_KEY: ${SECRET_KEY:-change-me}
      NEWME_USERS: ${NEWME_USERS:-}
      OLLAMA_HOSTS: ${OLLAMA_HOSTS:-merl|http://merl.clasp.gu.se,lark|http://lark.clasp.gu.se,localhost|http://127.0.0.1:11434}
    volumes:
      - ./data:/data
    command: gunicorn --bind=0.0.0.0:8060 newme.wsgi:app
    restart: unless-stopped
