"""add prompts table

Revision ID: 238a6b5f1b6e
Revises: cf79934710fd
Create Date: 2026-04-24 13:09:29.411670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238a6b5f1b6e'
down_revision = 'cf79934710fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('num_ctx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_experiment_id'), ['experiment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_experiment_id'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
