"""add regex_patterns to user_settings

Revision ID: 831d44d2e7ae
Revises: 08b29aa4b8aa
Create Date: 2026-05-12 13:27:42.337935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831d44d2e7ae'
down_revision = '08b29aa4b8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regex_patterns', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('regex_patterns')

    # ### end Alembic commands ###
